<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Listado Canciones</title>
    </head>
    <body>
	 <div class="form-group">
		<label for="canciones">Canciones:</label>
		<select name="cancion">
			<?php foreach($canciones as $cancion) : ?>
				<option> <?php echo $cancion?> </option>
			<?php endforeach; ?>
		</select>
	</div>
    </body>
</html>